#!/usr/bin/env python3
#
# Focus the first active output that isn't primary, if any, with fallback to
# primary.

import i3ipc

i3 = i3ipc.Connection()

name = 'primary'

for output in i3.get_outputs():
    if output.active and not output.primary:
        name = output.name
        break

i3.command(f'focus output {name}')
