#!/usr/bin/env python3
#
# Focus an output by index (0 = primary).
#
# bindsym $mod+w focus output primary
# bindsym $mod+e exec --no-startup-id scripts/focus_output 1

import i3ipc
import sys

i3 = i3ipc.Connection()

target = int(sys.argv[1])
outputs = [o for o in i3.get_outputs() if o.active]

if target < len(outputs):
  name = outputs[target].name
  i3.command(f'focus output {name}')
