#!/usr/bin/env python3

import i3ipc
import subprocess

i3 = i3ipc.Connection()

current_outputs = None

def handle_output_change(*args, **kwargs):
    global current_outputs
    new_outputs = sorted(map(lambda o: o.name, filter(lambda o: o.active, i3.get_outputs())))

    if new_outputs != current_outputs:
        print('Resetting background');
        current_outputs = new_outputs
        subprocess.run(['/usr/bin/nitrogen', '--restore'])

i3.on('output', handle_output_change)
handle_output_change()

i3.main()
