#!/usr/bin/env python3
#
# Run a command for resetting the background whenever monitors are
# (dis)connected or change resolution.

import i3ipc
import subprocess

i3 = i3ipc.Connection()

command = ['/usr/bin/nitrogen', '--restore']

current_outputs = None

def handle_output_change(*args, **kwargs):
    global current_outputs

    new_outputs = sorted((f'{o.name} {o.rect.width}x{o.rect.height}+{o.rect.x}x{o.rect.y}'
        for o in i3.get_outputs() if o.active))

    if new_outputs != current_outputs:
        print('Resetting background:', current_outputs, '->', new_outputs)
        try:
            subprocess.run(command, check=True)
            current_outputs = new_outputs
        except:
            print('Failed to reset background. Trying again next time.')
    else:
        print('Current outputs:', current_outputs)

i3.on('output', handle_output_change)
handle_output_change()

i3.main()
